version: '3.9'

services:
  pgdb:
    image: postgres:15-alpine
    container_name: pgdb
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    hostname: ${DB_HOST}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_COUNT_DB: ${REDIS_COUNT_DB}
    volumes:
      - redisdata:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot
    command: sh -c "python src/db/migrate.py && python src/main.py"
    restart: always
    env_file:
      - .env
    depends_on:
      - pgdb
      - redis
    volumes:
      - ./src:/app/src

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"  # Изменяем внешний порт с 9090 на 9091
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - pgdb
      - redis

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  postgres_exporter:
    image: bitnami/postgres-exporter:latest
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${DB_USER}:${DB_PASSWORD}@pgdb:5432/${DB_NAME}"
    ports:
      - "9187:9187"
    depends_on:
      - pgdb

  redis_exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter
    environment:
      REDIS_ADDR: "redis:${REDIS_PORT}"
    ports:
      - "9121:9121"
    depends_on:
      - redis

volumes:
  pgdata:
  redisdata:
  grafana_data:
