global:
  scrape_interval: 15s  # Интервал сбора метрик

scrape_configs:
  - job_name: 'pgdb'
    static_configs:
      - targets: ['postgres_exporter:9187']  # Экспортёр для PostgreSQL

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']  # Экспортёр для Redis
