name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connect, pull from repo and restart docker
        uses: appleboy/ssh-action@v1.0.3
        env:
          REMOTE_DIR: '/var/www/ai_python_interviewer'
          GIT_CONNECT: 'git@github.com:genius-paulo/ai_python_interviewer.git'
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          debug: true
          script_stop: true
          envs: REMOTE_DIR,GIT_CONNECT
          script: |
            if [ ! -d $REMOTE_DIR ]; then git clone $GIT_CONNECT $REMOTE_DIR; fi
            cd $REMOTE_DIR && git pull origin main
            docker compose -f docker-compose.yml up -d --build
